In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

<h1 style=color:red>Urinary Operations</h1>

<h2>Subtraction</h2>

In [3]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

<h2>Array Multiplication</h2>

In [4]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

<h2>Scaler Multiplication</h2>

In [5]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

<h2>Comparison</h2>

In [6]:
arr2>3

array([ True,  True,  True,  True,  True,  True])

<h2>Dot product</h2>

In [7]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

In [8]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

<h2>find maximum and minimum elements in array</h2>

In [9]:
arr4.max() #find maximum element

11

In [10]:
arr4.min() #find minimum element

6

In [11]:
arr4.min(axis=0) #find minimum element columnwise

array([6, 7])

In [12]:
arr4.min(axis=1) #find minimum element rowwise

array([ 6,  8, 10])

<h2>Calculate sum</h2>

In [13]:
arr4.sum(axis=0) #find sum columnwise

array([24, 27])

<h2>Calculate mean</h2>

In [14]:
arr4.mean()

8.5

<h2>Calculate median</h2>

In [15]:
np.median(arr4)

8.5

<h2>Calculate standard deviation</h2>

In [16]:
arr4.std()

1.707825127659933

<h2>Trigonometric functions</h2>

In [17]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

<h2>Calculate exponential</h2>

In [18]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

<h3>There are many more operation available in numpy</h3>