In [1]:
import numpy as np

<h3>Generate a random float number between 0 and 1</h3>

In [2]:
np.random.random()

0.35052201118797677

<h3>Set the random number generator to always produce the same numbers</h3>

In [5]:
np.random.seed(1)
np.random.random()

0.417022004702574

<h3>Generate a random float number between 3 and 10</h3>

In [6]:
np.random.uniform(3,10)

8.042271454095108

In [9]:
np.random.uniform(1,100,10).reshape(2,5)

array([[21.24077272, 87.9336262 ,  3.71137173, 67.37628351, 42.31317543],
       [56.31029302, 14.89830692, 20.61204742, 80.2737123 , 96.857896  ]])

random integers

<h3>Generate an array of 15 random integers between 1 and 9</h3>

In [12]:
np.random.randint(1,10,15).reshape(3,5)

array([[7, 6, 2, 4, 5],
       [9, 2, 5, 1, 4],
       [3, 1, 5, 3, 8]])

index of max/min

In [14]:
a=np.random.randint(1,10,6)
a

array([5, 6, 4, 7, 9, 1])

<h3>Find the index of the maximum value in the array 'a'</h3>

In [16]:
np.argmax(a)

4

<h3>Find the index of the minimum value in the array 'a'</h3>

In [17]:
np.argmin(a)

5

<h3>Replace all odd numbers in the array 'a' with -1 in original array</h3>

In [35]:
a=np.random.randint(1,10,6)
a

array([9, 8, 1, 4, 5, 3])

In [36]:
a[a%2==1]=-1
a

array([-1,  8, -1,  4, -1, -1])

<h3>Replace all odd numbers in the array 'a' with -1 but not in original array</h3>

In [37]:
a=np.random.randint(1,50,6)
a

array([15, 47,  1, 30, 12, 36])

In [38]:
np.where(a%2==1,-1,a) #numpy.where(condition, [x if true, y if false])

array([-1, -1, -1, 30, 12, 36])

In [39]:
a

array([15, 47,  1, 30, 12, 36])

In [41]:
out=np.where(a%2==1,-1,a)
out

array([-1, -1, -1, 30, 12, 36])

<h3>Calculate the nth percentile of the array 'a'</h3>

In [42]:
a=np.random.randint(1,50,10)
a

array([30, 34,  3, 21, 20, 49, 33, 29, 19, 32])

In [44]:
a=np.sort(a)
a

array([ 3, 19, 20, 21, 29, 30, 32, 33, 34, 49])

In [45]:
np.percentile(a,25) #numpy.percentile(a, percentile)

20.25

In [46]:
np.percentile(a,50)

29.5